author:
  name: Tobias Hinz
markdown: kramdown

title: PhD Student in Machine Learning at the University of Hamburg
description: I work with Neural Networks (Deep Learning) in Computer Vision and Natural Language Processing to understand and describe the world around us.
url: "https://tohinz.github.io"
baseurl: ""

social:
  name: Tobias Hinz
  links:
    - https://www.linkedin.com/in/tobias-hinz-397881123
    - https://github.com/tohinz
    - https://www.inf.uni-hamburg.de/en/inst/ab/wtm/people/hinz.html

# Jekyll Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Analytics
google_analytics: UA-135888913-1

disqus:
  shortname: https-tohinz-github-io
