author:
  name: Tobias Hinz
markdown: kramdown

title: Tobias Hinz
description: personal website of Tobias Hinz
url: "https://tohinz.github.io/"
baseurl: ""

# Jekyll Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Analytics
google_analytics: UA-135888913-1

disqus:
  shortname: https://https-tohinz-github-io
