author:
  name: Tobias Hinz
markdown: kramdown

url: "https://tohinz.github.io"
baseurl: ""

# SEO Configuration - Explicitly ensure indexing
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      robots: "index, follow"

social:
  name: Tobias Hinz
  links:
    - https://www.linkedin.com/in/tobias-hinz-397881123
    - https://github.com/tohinz

# Jekyll Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

# Google Analytics
google_analytics: UA-135888913-1

disqus:
  shortname: https-tohinz-github-io

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
